### ISSUE TITLE
POTATO Briefing Template incorrect Friendly Forces

### ISSUE THREAD

**Issue by RetroSpectra** [tanaaKa/CMF3#10]
![Model viewer 8_1_2023 12_18_49 AM](https://github.com/tanaaKa/CMF3/assets/77911631/8fbebafc-ec7d-4e1e-acd3-549c278bd8c7)

Briefing template in the mission section has "FRIENDLY" heading and text talking about enemy forces, vice versa for "ENEMY" heading. Both on OPFOR and BLUFOR.

**Comment by tanaaKa** [comment]
Fixed in https://github.com/tanaaKa/CMF3/commit/fa54c688a9f437ce900c4c116c28efeda535b90d
