### ISSUE TITLE
OPFOR Lobby slotting in wrong order

### ISSUE THREAD

**Issue by RetroSpectra** [tanaaKa/CMF3#8]
OPFOR Infantry Squads are shown slotting as:

Squad Leader
Team Leader (2IC)
Assistant Automatic Rifleman
Team Leader (3IC)
Rifleman (AT)
Rifleman (AT)
Rifleman (CLS)
**Automatic Rifleman**

Recommend moving to mirror BLUFOR structure, which is:

Squad Leader
Team Leader (2IC)
**Automatic Rifleman**
Assistant Automatic Rifleman
Team Leader (3IC)
Rifleman (AT)
Rifleman (AT)
Rifleman (CLS)

**Comment by tanaaKa** [comment]
Fixed in https://github.com/tanaaKa/CMF3/commit/fa54c688a9f437ce900c4c116c28efeda535b90d
