### ISSUE TITLE
Polygonal Map Cover comments incorrect

### ISSUE THREAD

**Issue by RetroSpectra** [tanaaKa/CMF3#9]
Comments in editor on map state to uncomment line 12 in initServer.sqf to enable Polygonal Map Cover.

initServer.sqf does not have a line 12
Polygonal Map Cover is enabled by default in initPlayerLocal.sqf

**Comment by tanaaKa** [comment]
Fixed in https://github.com/tanaaKa/CMF3/commit/fa54c688a9f437ce900c4c116c28efeda535b90d
